# Generated by Django 5.2.4 on 2025-07-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when prescription was created.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the doctor.', null=True)),
                ('doctor', models.ForeignKey(help_text='Doctor who wrote this prescription.', limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient receiving this prescription.', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text='Dosage instructions, e.g. "500mg twice daily".', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Total quantity of this drug prescribed.')),
                ('drug', models.ForeignKey(help_text='Drug being prescribed.', on_delete=django.db.models.deletion.PROTECT, related_name='prescription_drugs', to='inventory.drug')),
                ('prescription', models.ForeignKey(help_text='Prescription to which this drug belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Drug',
                'verbose_name_plural': 'Prescription Drugs',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'date'], name='prescriptio_doctor__09fe36_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'date'], name='prescriptio_patient_c46daf_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiondrug',
            index=models.Index(fields=['drug'], name='prescriptio_drug_id_98e03f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptiondrug',
            unique_together={('prescription', 'drug')},
        ),
    ]
