# Generated by Django 5.2.4 on 2025-07-12 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(help_text='Doctor specialty, e.g. Cardiology', max_length=100)),
                ('schedule', models.JSONField(blank=True, help_text='Weekly availability JSON, e.g. {"monday": ["09:00-12:00", "14:00-17:00"], …}', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
                'indexes': [models.Index(fields=['user'], name='doctors_doc_user_id_cfa9b1_idx'), models.Index(fields=['specialty'], name='doctors_doc_special_01789e_idx')],
            },
        ),
    ]
