# Generated by Django 5.2.4 on 2025-07-12 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '__first__'),
        ('prescriptions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units to dispense.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', help_text='Order lifecycle status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(help_text='Drug being ordered.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.drug')),
                ('patient', models.ForeignKey(help_text='Patient placing the order.', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text='Prescription this order fulfills.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'indexes': [models.Index(fields=['patient'], name='orders_orde_patient_1eb610_idx'), models.Index(fields=['prescription'], name='orders_orde_prescri_c26507_idx'), models.Index(fields=['drug'], name='orders_orde_drug_id_e96852_idx')],
            },
        ),
    ]
