name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports: ["6379:6379"]
      db:
        image: postgres:15
        env:
          POSTGRES_DB: clinicxdb
          POSTGRES_USER: clinicxuser
          POSTGRES_PASSWORD: clinicxpass
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U clinicxuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U clinicxuser; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Run migrations
        run: |
          python manage.py migrate --no-input

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
